name: Tests
on: [push, pull_request]
jobs:
   gcc-musl:
      runs-on: ubuntu-latest
      container: voidlinux/voidlinux-musl
      steps:
         - uses: actions/checkout@v1
         - run: xbps-install -Sy gcc make bearssl-devel
         - run: ci/run.sh
   clang-glibc:
      runs-on: ubuntu-latest
      container: voidlinux/voidlinux
      steps:
         - uses: actions/checkout@v1
         - run: xbps-install -Sy clang make bearssl-devel
         - run: CC=clang ci/run.sh
